### ISSUE TITLE
Tutorial HUD disabling timer HUD

### ISSUE THREAD

**Issue by Novaclone** [ScrewdriverHyena/ParkourFortress-Bugs#106] opened 2020-05-27 06:03 UTC
It seems to be occurring for every map so far that I've played. The tutorial HUD always pops up whenever I join a map for the first time. I can complete the tutorial, but the timer HUD doesn't pop up after I finish the tutorial nor do I respawn at the start of the map after completing the tutorial. The !tutorial commands doesn't seem to work after I try to complete the tutorial. Also the parkour arms animations seem to be broken as a result. The timer still seems usable it gives a time when I complete the map.

**Comment by ScrewdriverHyena** [comment] 2020-05-27 07:29
Was your timer rank different from usual per chance? This seems like something that would be caused by an issue with steam on your end. Let me know if not and I'll look into it.

**Comment by Novaclone** [comment] 2020-05-27 08:39
It doesn't seem like it did. My rank seems to be unaffected overall. It's the timer HUD with the speedometer that's not showing up.
![20200527013203_1](https://user-images.githubusercontent.com/65998290/82997185-e7ce1e80-9fba-11ea-9535-26ee28348f2d.jpg)

**Comment by ScrewdriverHyena** [comment] 2020-05-27 08:49
Do you know if this is happening to any other players?

**Comment by Novaclone** [comment] 2020-05-27 09:17
I am not sure.

**Comment by ScrewdriverHyena** [comment] 2020-05-27 20:32
This seems to be fixed but I'm suspicious about how, so I'm going to be leaving this issue open. If it doesn't happen again within the next week I'll go ahead and close the issue.

**Closed** 2020-08-20 23:34 UTC
