### ISSUE TITLE
Softlock when doing roll animation at spawn

### ISSUE THREAD

**Issue by Son-Dream** [ScrewdriverHyena/ParkourFortress-Bugs#51] opened 2019-08-24 00:55 UTC
If you do the roll animation from falling down whilst landing into the spawn area that resets time, you'll be trapped in a permanent roll ball, and be unable to move or reset. Got this one while jumping off the catwalk at the beginning of pf_kijun. I was able to recreate this one at hekto, and have been trying it at other maps as well.

![20190823193440_1](https://user-images.githubusercontent.com/46637312/63630397-ced5ae80-c5df-11e9-8cbb-db4eeae7a4ef.jpg)

**Comment by namishere** [comment] 2019-08-24 05:36
Cannot replicate. Intended behavior, and what was encountered during testing, is that landing in the spawn area sets you in a state where you aren't able to roll.
Please use "record [demo name]" in the console to record this happening, followed by "stop" to end the recording, and then upload the [demo name].dem file found in your Team Fortress 2/tf folder either here or to me directly on Discord (Nami#7660).

**Comment by ScrewdriverHyena** [comment] 2019-12-17 13:40
This was fixed a while ago and not closed, closing.

**Closed by ScrewdriverHyena** 2019-12-17 13:40 UTC
