### ISSUE TITLE
Ledge grab height bug

### ISSUE THREAD

**Issue by shuk-fuk** [ScrewdriverHyena/ParkourFortress-Bugs#65] opened 2019-10-23 03:20 UTC
Not sure if holding crouch is required, but if you release crouch right under a ledge while holding forward you can grab under the ledge. It's always a 20 hu difference.

https://steamcommunity.com/sharedfiles/filedetails/?id=1896482934

https://steamcommunity.com/sharedfiles/filedetails/?id=1896482943

**Comment by ScrewdriverHyena** [comment] 2019-11-13 13:22
This is a tough one- I believe it's caused by how we check for ledges in general, so this very thin ledge doesn't exactly sit well with our traces. Will keep as low-prio until a good fix is found.

**Comment by ScrewdriverHyena** [comment] 2020-05-01 23:14
This isn't happening anymore from what I'm aware so I'm going to close this issue, if it's still happening let me know.

**Closed by ScrewdriverHyena** 2020-05-01 23:14 UTC
Labels: bug, low-priority
